#!/usr/bin/env python3
"""
Render the release-watcher's commit message body from env vars.

Reads:
- Env: NEW_VERSION (e.g. "1.6.1"), OLD_VERSION (e.g. "1.5.0"),
       IS_MAJOR ("true"|"false")

Writes the multi-line commit message to stdout. The watcher pipes this
into `git commit -F -`.

Why this exists: the watcher used to build this message via a bash
heredoc that wrapped the workflow filename `maf-ai-fill-todos.yml` in
backticks. In a double-quoted bash string, backticks are command
substitution — bash tried to execute `maf-ai-fill-todos.yml` as a command
and the watcher run aborted with exit 127. We moved the rendering to
Python so there is no shell tokenisation at all.
"""
import os
import sys


def main() -> int:
    new_version = os.environ.get("NEW_VERSION", "").strip()
    old_version = os.environ.get("OLD_VERSION", "").strip()
    is_major = os.environ.get("IS_MAJOR", "false").strip().lower() == "true"

    if not new_version:
        print("ERROR: NEW_VERSION env var is required", file=sys.stderr)
        return 1
    if not old_version:
        print("ERROR: OLD_VERSION env var is required", file=sys.stderr)
        return 1

    kind = "MAJOR " if is_major else ""
    lines = [
        f"chore: auto-update MAF {kind}registry for {new_version}",
        "",
        f"Bumped from {old_version} -> {new_version}.",
        "",
        "Auto-generated by .github/workflows/maf-release-watcher.yml.",
        "TODO fields are filled on this PR branch by the maf-registry-fill",
        "agentic workflow, then gated by maf-ai-fill-verify before merge.",
    ]
    sys.stdout.buffer.write(("\n".join(lines) + "\n").encode("utf-8"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
