using System.Text.RegularExpressions;
using MafDoctor.Data;

namespace MafDoctor.Commands;

/// <summary>
/// CLI: <c>maf-doctor verify-registry</c>.
///
/// **#5 polish (2026-05-13)** — the verification gate for the AI-fill flow.
/// After GitHub Copilot Coding Agent fills the TODO placeholders in
/// <c>registry.yaml</c>, the PR-triggered workflow
/// <c>.github/workflows/maf-ai-fill-verify.yml</c> runs this command to catch
/// the common failure modes BEFORE the PR is merged.
///
/// **What it checks** (per entry):
/// <list type="bullet">
///   <item><c>fix_description</c> is at least 20 chars (not empty / "TODO").</item>
///   <item><c>example_before</c> is non-empty.</item>
///   <item><c>example_after</c> is non-empty.</item>
///   <item><c>example_before</c> != <c>example_after</c> (a real migration shows a change).</item>
///   <item>Both examples have balanced <c>{}</c> and <c>()</c>.</item>
///   <item><c>cs_warning</c> matches <c>CS\d{4}</c>, <c>RUNTIME_SILENT</c>, or <c>BINARY_BREAK</c>.</item>
///   <item><c>guide_section</c> is not the literal "TODO" / "TBD" (use "N/A" if no parallel).</item>
///   <item><c>applies_to_codebases</c> is present and well-formed on EVERY entry (Q-03).</item>
/// </list>
///
/// **Exit code:** 0 on success; 1 on any verification failure (with per-entry
/// detail emitted to stderr).
///
/// Skipping rule: entries marked exactly <c>applies_to_codebases: "pre-1.0.0"</c> are
/// SKIPPED — they're documentation of historical patterns, not migration
/// targets, so their examples may reference removed types intentionally.
/// </summary>
public static class VerifyRegistryCommand
{
    public static int Run()
    {
        var registry = new RegistryService();
        var issues = new List<string>();
        var skippedHistorical = 0;
        var skippedIncompleteDrafts = 0;

        // IDs are the registry's join key across diagnostics, guides, and tools.
        // Detect collisions before any historical/draft skip so no duplicate can
        // evade the gate merely because one copy is not substantively validated.
        CheckDuplicateIds(registry.AllEntries, issues);

        foreach (var entry in registry.AllEntries)
        {
            // Q-03: the per-codebase filter treats a missing or malformed marker
            // as "applies to any version", so a forgotten marker silently widens
            // an entry. Enforce it on every entry, including historical/drafts.
            CheckAppliesToMarker(entry, issues);

            // Exact pre-1.0.0 entries are historical docs; their examples may
            // reference removed types deliberately. Skip the SUBSTANTIVE
            // checks (brace balance, placeholder detection) but ALWAYS run
            // the content-safety sweep — historical entries can still
            // accidentally or maliciously carry HTML-comment-disguised
            // injection or oversized payloads, and we serve them via
            // MafRegistryLookup the same way as fresh entries.
            if (IsHistoricalDocumentationEntry(entry))
            {
                skippedHistorical++;
                CheckContentSafety(entry, issues);
                continue;
            }

            // Incomplete drafts — entries where ANY core fillable field is still
            // a placeholder/empty (raw OR partially filled). Auto-generated by
            // `registry-extract` and filled incrementally by a human/Copilot.
            // Skip the structural checks (so filling is monotonic — never a
            // partial-fill trap) but STILL apply content safety (the embedded
            // dotnet-inspect diff is attacker-controllable upstream). Keep-
            // breaking-red for CURRENT-cycle drafts is enforced separately by the
            // Python cross-file gate, scoped to .maf-version.
            if (IsIncompleteDraft(entry))
            {
                skippedIncompleteDrafts++;
                CheckContentSafety(entry, issues);
                CheckCsWarning(entry, issues);
                continue;
            }

            CheckEntry(entry, issues);
        }

        if (issues.Count > 0)
        {
            Console.Error.WriteLine($"❌ Registry verification FAILED: {issues.Count} issue(s) across {registry.AllEntries.Count - skippedHistorical - skippedIncompleteDrafts} active entries ({skippedHistorical} historical (exact pre-1.0.0) + {skippedIncompleteDrafts} incomplete-draft entries skipped).");
            Console.Error.WriteLine();
            foreach (var issue in issues)
                Console.Error.WriteLine($"  • {issue}");
            Console.Error.WriteLine();
            Console.Error.WriteLine("Fix locally and re-run `maf-doctor verify-registry`.");
            return 1;
        }

        Console.WriteLine($"✓ Registry verification PASSED: {registry.AllEntries.Count - skippedHistorical - skippedIncompleteDrafts} active entries clean ({skippedHistorical} historical (exact pre-1.0.0) + {skippedIncompleteDrafts} incomplete-draft entries skipped).");
        return 0;
    }

    internal static bool IsHistoricalDocumentationEntry(RegistryEntry entry) =>
        string.Equals(
            entry.AppliesToCodebases?.Trim(),
            "pre-1.0.0",
            StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Requires an <c>applies_to_codebases</c> marker in one of the three forms
    /// <see cref="RegistryService.GetEntriesForCodebaseVersion"/> understands:
    /// <c>pre-X.Y.Z</c>, <c>X.Y.Z+</c>, or an exact <c>X.Y.Z</c>.
    /// </summary>
    internal static void CheckAppliesToMarker(RegistryEntry entry, List<string> issues)
    {
        var marker = entry.AppliesToCodebases?.Trim();
        if (string.IsNullOrEmpty(marker))
        {
            issues.Add($"{entry.Id}: applies_to_codebases is missing (use \"pre-X.Y.Z\", \"X.Y.Z+\" or an exact \"X.Y.Z\").");
            return;
        }

        var version = marker;
        if (version.StartsWith("pre-", StringComparison.OrdinalIgnoreCase))
            version = version[4..];
        else if (version.EndsWith('+'))
            version = version[..^1];

        var parts = version.Split('.');
        if (parts.Length != 3 || !parts.All(p => p.Length > 0 && p.All(char.IsAsciiDigit)))
            issues.Add($"{entry.Id}: applies_to_codebases '{marker}' is malformed (use \"pre-X.Y.Z\", \"X.Y.Z+\" or an exact \"X.Y.Z\").");
    }

    internal static void CheckDuplicateIds(
        IEnumerable<RegistryEntry> entries,
        List<string> issues)
    {
        var seen = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var entry in entries)
        {
            var id = entry.Id?.Trim();
            if (string.IsNullOrEmpty(id)) continue;
            if (seen.TryGetValue(id, out var firstSpelling))
            {
                issues.Add($"duplicate registry id '{id}' conflicts with '{firstSpelling}' (IDs are case-insensitive).");
            }
            else
            {
                seen[id] = id;
            }
        }
    }

    /// <summary>
    /// Regex matching a <c>// TODO</c> marker AT THE START of a line (after
    /// optional whitespace). Phase 2.8 tightened this from a substring check
    /// because a string literal like <c>"// TODO refactor"</c> embedded in
    /// otherwise-real code would falsely re-qualify the entry as a raw draft
    /// and bypass the substantive checks entirely.
    ///
    /// Uses an explicit ASCII boundary (not \b) — same cross-engine rationale as
    /// PlaceholderTokenRegex; kept identical to Python _TODO_EXAMPLE_RE.
    /// </summary>
    private static readonly Regex TodoAtLineStart = new(
        @"(?m)^\s*//\s*TODO(?:[^A-Za-z0-9_]|$)",
        RegexOptions.Compiled | RegexOptions.NonBacktracking | RegexOptions.IgnoreCase,
        TimeSpan.FromSeconds(2));

    private static readonly Regex CsWarningRegex = new(
        @"^(?:CS[0-9]{4}|RUNTIME_SILENT|BINARY_BREAK)$",
        RegexOptions.Compiled | RegexOptions.NonBacktracking,
        TimeSpan.FromSeconds(2));

    /// <summary>
    /// True when EVERY fillable core field is a TODO/placeholder — the fully-raw
    /// "auto-generated by `registry-extract`, never filled" state. Note
    /// <see cref="IsIncompleteDraft"/> is the broader (ANY-field) gate actually
    /// used by <see cref="Run"/>; this stricter all-fields predicate is retained
    /// for the raw-draft detection tests.
    /// </summary>
    internal static bool IsRawDraft(RegistryEntry entry)
    {
        return LooksLikePlaceholder(entry.ObsoleteSignature)
            && LooksLikePlaceholder(entry.ReplacementSignature)
            && LooksLikePlaceholderOrStartsWith(entry.FixDescription, "TODO")
            && TodoAtLineStart.IsMatch(entry.ExampleBefore ?? string.Empty)
            && TodoAtLineStart.IsMatch(entry.ExampleAfter ?? string.Empty)
            && LooksLikePlaceholder(entry.CsWarning);
    }

    /// <summary>
    /// True when ANY core fillable field is still a placeholder or empty — i.e.
    /// the entry is not YET fully filled (raw OR partially filled). The
    /// structural checks are SKIPPED for such entries, which makes incremental
    /// filling MONOTONIC: filling one field of a draft never converts a "skipped"
    /// entry into a pile of new CheckEntry failures (the old partial-fill trap,
    /// where <see cref="IsRawDraft"/>'s all-fields-AND flipped a one-field-filled
    /// entry into full validation). An entry graduates to full checks only once
    /// every core field is filled.
    ///
    /// This does NOT weaken keep-breaking-red: the Python cross-file gate
    /// (verify_crossfile_consistency.check_unfilled_current_drafts, scoped to the
    /// current .maf-version) still BLOCKS an unfilled CURRENT-cycle draft. This
    /// method only governs whether the C# structural/content checks run — and the
    /// field-level predicates here mirror that gate's _looks_unfilled /
    /// _example_unfilled / cs_warning checks (shared placeholder grammar,
    /// Option 1).
    /// </summary>
    internal static bool IsIncompleteDraft(RegistryEntry entry)
    {
        return IsUnfilled(entry.ObsoleteSignature)
            || IsUnfilled(entry.ReplacementSignature)
            || IsUnfilled(entry.FixDescription)
            || IsExampleUnfilled(entry.ExampleBefore)
            || IsExampleUnfilled(entry.ExampleAfter)
            || IsUnfilled(entry.CsWarning);
    }

    /// <summary>A required field is unfilled when it is empty or a placeholder token.</summary>
    private static bool IsUnfilled(string? s)
        => string.IsNullOrWhiteSpace(s) || LooksLikePlaceholder(s);

    /// <summary>An example field is unfilled when empty or still the `// TODO` stub.</summary>
    private static bool IsExampleUnfilled(string? s)
        => string.IsNullOrWhiteSpace(s) || TodoAtLineStart.IsMatch(s);

    /// <summary>
    /// Minimal content-safety sweep applied even to entries we'd otherwise
    /// skip (pre-1.0 historical, raw drafts). Catches the prompt-injection
    /// and oversized-payload classes; ignores stylistic / structural issues.
    /// </summary>
    internal static void CheckContentSafety(RegistryEntry entry, List<string> issues)
    {
        const int notesCap = 16 * 1024;
        const int exampleCap = 32 * 1024;

        var (fixDesc, before, after, notes) = (
            entry.FixDescription ?? string.Empty,
            entry.ExampleBefore ?? string.Empty,
            entry.ExampleAfter ?? string.Empty,
            entry.Notes ?? string.Empty);

        // Length caps — bound DoS surface and prevent context-window flooding
        // when registry entries flow into LLM prompts via MafRegistryLookup.
        if (fixDesc.Length > notesCap)
            issues.Add($"{entry.Id}: fix_description exceeds {notesCap} bytes ({fixDesc.Length}).");
        if (before.Length > exampleCap)
            issues.Add($"{entry.Id}: example_before exceeds {exampleCap} bytes ({before.Length}).");
        if (after.Length > exampleCap)
            issues.Add($"{entry.Id}: example_after exceeds {exampleCap} bytes ({after.Length}).");
        if (notes.Length > notesCap)
            issues.Add($"{entry.Id}: notes exceeds {notesCap} bytes ({notes.Length}).");

        // HTML comments — the most common prompt-injection vector in markdown.
        // A pre-1.0 historical entry has no reason to legitimately carry an
        // HTML comment in its prose fields. (Real code in example_* may
        // contain `<!-- -->` inside a string literal, so we exempt those.)
        if (HtmlCommentRegex.IsMatch(fixDesc))
            issues.Add($"{entry.Id}: fix_description contains an HTML comment (prompt-injection vector).");
        if (HtmlCommentRegex.IsMatch(notes))
            issues.Add($"{entry.Id}: notes contains an HTML comment (prompt-injection vector).");
    }

    private static readonly Regex HtmlCommentRegex = new(
        @"<!--[\s\S]*?-->",
        RegexOptions.Compiled | RegexOptions.NonBacktracking,
        TimeSpan.FromSeconds(2));

    private static bool LooksLikePlaceholderOrStartsWith(string? s, string prefix)
    {
        if (LooksLikePlaceholder(s)) return true;
        return !string.IsNullOrWhiteSpace(s)
            && s.Trim().StartsWith(prefix, StringComparison.OrdinalIgnoreCase);
    }

    internal static void CheckEntry(RegistryEntry entry, List<string> issues)
    {
        CheckCsWarning(entry, issues);

        // fix_description must exist and be substantial.
        if (string.IsNullOrWhiteSpace(entry.FixDescription))
            issues.Add($"{entry.Id}: fix_description is empty.");
        else if (entry.FixDescription.Trim().Length < 20)
            issues.Add($"{entry.Id}: fix_description is too short (< 20 chars): \"{entry.FixDescription.Trim()}\"");
        else if (LooksLikePlaceholder(entry.FixDescription))
            issues.Add($"{entry.Id}: fix_description looks like a placeholder (TODO/TBD/...): \"{entry.FixDescription.Trim()}\"");

        // example_before + example_after must exist + differ + balance.
        if (string.IsNullOrWhiteSpace(entry.ExampleBefore))
            issues.Add($"{entry.Id}: example_before is empty.");
        if (string.IsNullOrWhiteSpace(entry.ExampleAfter))
            issues.Add($"{entry.Id}: example_after is empty.");
        if (!string.IsNullOrWhiteSpace(entry.ExampleBefore)
            && !string.IsNullOrWhiteSpace(entry.ExampleAfter)
            && entry.ExampleBefore.Trim() == entry.ExampleAfter.Trim())
        {
            issues.Add($"{entry.Id}: example_before == example_after (no migration shown).");
        }

        // Brace balance — quick syntactic sanity. Roslyn-parsing fragments
        // gives false negatives (parser is forgiving), so we use the cheaper
        // depth-aware counter as a "did the Copilot Agent leave half a
        // snippet" check. Depth-aware (not just delta) catches `}{` and
        // `}; evil(); {` — the count-only v1 version passed both.
        var beforeBraces = BraceBalanceFailure(entry.ExampleBefore);
        if (beforeBraces is not null)
            issues.Add($"{entry.Id}: example_before has unbalanced braces ({beforeBraces}).");
        var afterBraces = BraceBalanceFailure(entry.ExampleAfter);
        if (afterBraces is not null)
            issues.Add($"{entry.Id}: example_after has unbalanced braces ({afterBraces}).");

        // guide_section must be a number, "N/A", or empty (legacy). Reject
        // explicit placeholders left by the Copilot Agent's filler logic.
        if (LooksLikePlaceholder(entry.GuideSection))
            issues.Add($"{entry.Id}: guide_section is a placeholder (use 'N/A' for no parallel section): \"{entry.GuideSection.Trim()}\"");
    }

    internal static void CheckCsWarning(RegistryEntry entry, List<string> issues)
    {
        var warning = entry.CsWarning?.Trim();
        if (string.IsNullOrWhiteSpace(warning))
            issues.Add($"{entry.Id}: cs_warning is empty.");
        else if (LooksLikePlaceholder(warning))
            issues.Add($"{entry.Id}: cs_warning is a placeholder: \"{warning}\".");
        else if (!CsWarningRegex.IsMatch(warning))
            issues.Add($"{entry.Id}: cs_warning must match CS\\d{{4}}, RUNTIME_SILENT, or BINARY_BREAK (got \"{warning}\").");
    }

    /// <summary>
    /// Depth-aware bracket nesting check. Maintains a stack of opening
    /// brackets (<c>{</c> / <c>(</c>) and verifies each closer matches the
    /// most recent opener — catches BOTH the same-family imbalance class
    /// (`}{`, `}; evil(); {`) AND the cross-family ordering class (`({)}`)
    /// that v1's delta-count missed. Returns <c>null</c> on success or a
    /// short human-readable description of the first failure.
    /// </summary>
    internal static string? BraceBalanceFailure(string? source)
    {
        if (string.IsNullOrEmpty(source)) return null;
        var stack = new Stack<char>();
        foreach (var c in source)
        {
            switch (c)
            {
                case '{':
                case '(':
                    stack.Push(c);
                    break;
                case '}':
                    if (stack.Count == 0) return "'}' before matching '{'";
                    if (stack.Pop() != '{') return "'}' closes a '(' (mismatched bracket types before matching)";
                    break;
                case ')':
                    if (stack.Count == 0) return "')' before matching '('";
                    if (stack.Pop() != '(') return "')' closes a '{' (mismatched bracket types before matching)";
                    break;
            }
        }
        if (stack.Count > 0)
        {
            var open = stack.Peek();
            return open == '{'
                ? $"{stack.Count} unmatched '{{'"
                : $"{stack.Count} unmatched '('";
        }
        return null;
    }

    /// <summary>
    /// Preserved for backward compatibility with any external callers; new
    /// callers should prefer <see cref="BraceBalanceFailure"/>. Returns the
    /// signed delta count (zero ≠ balanced — see <c>}{</c>).
    /// </summary>
    [Obsolete("Use BraceBalanceFailure for depth-aware detection; this returns delta only.")]
    internal static int BraceImbalance(string source)
    {
        var imbalance = 0;
        foreach (var c in source)
        {
            if (c is '{' or '(') imbalance++;
            else if (c is '}' or ')') imbalance--;
        }
        return imbalance;
    }

    /// <summary>
    /// A leading TODO/TBD/XXX word-token — the SHARED "placeholder" grammar.
    /// Kept byte-identical to the Python gate's <c>_DRAFT_PLACEHOLDER</c>
    /// (verify_crossfile_consistency.py) so the two gates can never disagree,
    /// and locked to <c>placeholder-fixtures.json</c> by cross-language tests
    /// (a C# test and a Python test assert the same table). It catches the
    /// extractor's default <c>"TODO — …"</c> (em-dash) too — the historical
    /// divergence — while a real identifier like <c>"TODOList"</c> is not. Empty
    /// is NOT a token (callers handle empty per field).
    ///
    /// The boundary is an explicit ASCII char-class, NOT <c>\b</c>: .NET and
    /// Python disagree on <c>\b</c>'s Unicode word-class (Mn/No/Nl/Pc categories
    /// flip the verdict for ~1400 code points, e.g. <c>"TODO²"</c>), which would
    /// re-open the same-string-opposite-verdict bug. The ASCII class is identical
    /// on both engines AND NonBacktracking-safe (no lookaround). Kept in lockstep
    /// with Python <c>_DRAFT_PLACEHOLDER</c> + placeholder-fixtures.json.
    /// </summary>
    private static readonly Regex PlaceholderTokenRegex = new(
        @"^\s*(?:TODO|TBD|XXX)(?:[^A-Za-z0-9_]|$)",
        RegexOptions.Compiled | RegexOptions.NonBacktracking | RegexOptions.IgnoreCase,
        TimeSpan.FromSeconds(2));

    /// <summary>True if a string begins with a TODO/TBD/XXX placeholder token.</summary>
    internal static bool LooksLikePlaceholder(string? s)
    {
        if (string.IsNullOrWhiteSpace(s)) return false;
        return PlaceholderTokenRegex.IsMatch(s);
    }
}
