using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace MafDoctor.Analyzers;

/// <summary>
/// MAF001 — fan-out handler must return ValueTask&lt;T&gt; (or a synchronous T).
///
/// Detects the silent fan-in starvation pattern at WRITE-TIME, before the
/// developer ever commits. A [MessageHandler] method that returns void,
/// Task, or ValueTask (non-generic) and does not emit through the workflow
/// context produces NO output message — the fan-in barrier then starves
/// silently. This is not a build error; without an analyzer, only static
/// scanning (post-edit) or runtime tracing catches it.
///
/// Only that shape is reported. A synchronous T or ValueTask&lt;T&gt; sends its value
/// (checked on Microsoft.Agents.AI.Workflows 1.23); Task&lt;T&gt; already fails the
/// source generator (MAFGENWF002); IAsyncEnumerable&lt;T&gt; fails at run time and is
/// reported by MafValidateFanOut.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class FanOutHandlerAnalyzer : DiagnosticAnalyzer
{
    public const string DiagnosticId = "MAF001";

    private static readonly LocalizableString Title =
        "Fan-out handler must return ValueTask<T>";

    private static readonly LocalizableString MessageFormat =
        "Method '{0}' is decorated with [MessageHandler] but returns '{1}' — this produces no downstream message and silently starves the fan-in barrier. Return ValueTask<T> where T is the downstream message type (Task<T> is rejected by the source generator, MAFGENWF002).";

    private static readonly LocalizableString Description =
        "A [MessageHandler] method that returns void, Task, or ValueTask (non-generic) produces no output. The workflow exits cleanly but incompletely — invisible to dotnet build, visible only at runtime. Return a typed ValueTask<TMessage> (the source generator rejects Task<TMessage>, MAFGENWF002).";

    private static readonly DiagnosticDescriptor Rule = new(
        id: DiagnosticId,
        title: Title,
        messageFormat: MessageFormat,
        category: "MAF.Workflow",
        // Warning, not Error: the analyzer sees one method, not the workflow topology,
        // so it cannot tell a fan-out source from a sink that legitimately returns nothing.
        // Raise it with `dotnet_diagnostic.MAF001.severity = error` to fail CI.
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: Description,
        helpLinkUri: "https://github.com/joslat/maf-doctor/blob/main/.github/skills/maf-fan-out-validator/SKILL.md");

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
        ImmutableArray.Create(Rule);

    public override void Initialize(AnalysisContext context)
    {
        // Phase 4.5 originally flipped this to `Analyze | ReportDiagnostics`
        // for consistency with MAF002/003. Phase 4.G review flagged that as a
        // FAR-too-aggressive change for MAF001 specifically: MAF001 was
        // severity Error at the time (Warning since 2026-10), and MAF source-
        // generators legitimately emit partial `[MessageHandler]` methods
        // whose return type is set by a separate user file — the analyzer
        // sees the generated half in isolation and flags it. Build-time
        // errors on code the user didn't write is a hostile UX.
        //
        // Phase 4.G fixup: keep `Analyze` (so the analyzer can SEE generated
        // code for context — e.g. to know the partial half exists) but DROP
        // `ReportDiagnostics` so no warning fires on a `<auto-generated>`
        // tree. MAF002 and MAF003 are Warning severity and their patterns
        // are unlikely in generated code, so they stay on both flags.
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.Analyze);
        context.EnableConcurrentExecution();
        context.RegisterSyntaxNodeAction(AnalyzeMethod, SyntaxKind.MethodDeclaration);
    }

    private static void AnalyzeMethod(SyntaxNodeAnalysisContext context)
    {
        var method = (MethodDeclarationSyntax)context.Node;
        if (!HasMessageHandlerAttribute(method)) return;

        var returnType = method.ReturnType.ToString().Trim();
        if (!ProducesNoValue(returnType) || EmitsThroughContext(method)) return;

        var diagnostic = Diagnostic.Create(
            Rule,
            method.ReturnType.GetLocation(),
            method.Identifier.ValueText,
            returnType);
        context.ReportDiagnostic(diagnostic);
    }

    private static bool HasMessageHandlerAttribute(MethodDeclarationSyntax method) =>
        method.AttributeLists
            .SelectMany(list => list.Attributes)
            .Any(attr =>
            {
                var name = attr.Name.ToString();
                var simpleName = name.Contains(".") ? name.Substring(name.LastIndexOf('.') + 1) : name;
                return simpleName == "MessageHandler" || simpleName == "MessageHandlerAttribute";
            });

    // void, Task or ValueTask (non-generic): the handler returns no message.
    private static bool ProducesNoValue(string returnType)
    {
        var simple = returnType.Contains(".")
            ? returnType.Substring(returnType.LastIndexOf('.') + 1)
            : returnType;
        return simple == "void" || simple == "Task" || simple == "ValueTask";
    }

    // context.SendMessageAsync / YieldOutputAsync / AddEventAsync: the handler emits
    // without returning a value — the documented void / ValueTask pattern.
    private static bool EmitsThroughContext(MethodDeclarationSyntax method)
    {
        var body = (SyntaxNode?)method.Body ?? method.ExpressionBody;
        if (body == null) return false;
        return body.DescendantNodes().OfType<InvocationExpressionSyntax>().Any(invocation =>
        {
            SimpleNameSyntax? name = invocation.Expression switch
            {
                MemberAccessExpressionSyntax member => member.Name,
                SimpleNameSyntax simple => simple,
                _ => null,
            };
            var text = name?.Identifier.ValueText;
            return text == "SendMessageAsync" || text == "YieldOutputAsync" || text == "AddEventAsync";
        });
    }
}
